name: "Auto Deploy"
on:
  push:
    branches: 
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: |
            cd pwcollections/pwcwebapp
            supervisorctl stop pwcwebapp
            git stash
            git stash clear
            git pull
            /bin/bun i
            /bin/bun run build
            supervisorctl start pwcwebapp
          host: cloud8point5.com
          user: github
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
